AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  GeneratePresignedURLFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/generate_presigned_url
      Handler: generate_presigned_url.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaApplicationRoleSam'

  CreateReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/create_report
      Handler: create_report.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaApplicationRoleSam'
      Events:
        CreateReport:
          Type: Api
          Properties:
            RestApiId: !Ref BikeAPI
            Path: /create-report
            Method: post

  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaApplicationRoleSam'
      DefinitionSubstitutions:
        GenerateHTMLArn: !GetAtt GenerateHTMLFunction.Arn #NEWLY ADDED
        GeneratePresignedURLArn: !GetAtt GeneratePresignedURLFunction.Arn
        GenerateReportDataArn: !GetAtt GenerateReportDataFunction.Arn #NEWLY ADDED
        SNSTopicArn: !Ref SNSTopic
      Definition:
        Comment: Report Generation State Machine
        StartAt: GenerateReportData #NEWLY ADDED
        States:
          GenerateReportData: #NEWLY ADDED
            Type: Task #NEWLY ADDED
            Resource: "${GenerateReportDataArn}" #NEWLY ADDED
            Next: Parallel #NEWLY ADDED
          Parallel: #NEWLY ADDED
            Type: Parallel #NEWLY ADDED
            Branches: #NEWLY ADDED
              - StartAt: GenerateHTML #NEWLY ADDED
                States: #NEWLY ADDED
                  GenerateHTML: #NEWLY ADDED
                    Type: Task #NEWLY ADDED
                    Resource: "${GenerateHTMLArn}" #NEWLY ADDED
                    End: true #NEWLY ADDED
              - StartAt: GeneratePresignedURL #NEWLY ADDED
                States: #NEWLY ADDED
                  GeneratePresignedURL: #NEWLY ADDED
                    Type: Task #NEWLY ADDED
                    Resource: "${GeneratePresignedURLArn}"
                    End: true #NEWLY ADDED
            Next: TriggerSNS
          TriggerSNS:
            Type: Task
            Resource: arn:aws:states:::sns:publish
            Parameters:
              TopicArn: "${SNSTopicArn}"
              Message.$: "$"
            End: true



  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: EmailReport
  
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: email
      Endpoint: metony157@gmail.com # REPLACE WITH VALID EMAIL

  BikeAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
            CognitoAuthorizer:
              UserPoolArn: !GetAtt "CognitoUserPool.Arn"

  ProductsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Products
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  OrdersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Orders
      AttributeDefinitions:
      -
        AttributeName: id
        AttributeType: S
      KeySchema:
      -
        AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  InventoryTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Inventory
      AttributeDefinitions:
      -
        AttributeName: id
        AttributeType: S
      KeySchema:
      -
        AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
        
  GetProductsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: handlers/get_products
      Handler: get_products.lambda_handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaApplicationRoleSam'
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        GetProducts:
          Type: Api 
          Properties:
            RestApiId: !Ref BikeAPI
            Path: /get_products
            Method: get
            
  GetOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get_orders
      Handler: get_orders.lambda_handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaApplicationRoleSam'
      Runtime: python3.10
      Architectures:
      - x86_64
      Events:
        GetOrders:
          Type: Api
          Properties:
            RestApiId: !Ref BikeAPI
            Path: /orders
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer

  GetOrderDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get_order
      Handler: get_order.lambda_handler
      Runtime: python3.10
      Architectures:
      - x86_64
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaApplicationRoleSam'
      Events:
        GetOrderDetails:
          Type: Api
          Properties:
            RestApiId: !Ref BikeAPI
            Path: /orders/{order_id}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer

  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/create_order
      Handler: create_order.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaApplicationRoleSam'
      Events:
        CreateOrder:
          Type: Api
          Properties:
            RestApiId: !Ref BikeAPI
            Path: /orders
            Method: post

  GenerateReportDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/generate_report_data
      Handler: generate_report_data.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaApplicationRoleSam'

  GenerateHTMLFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/generate_html
      Handler: generate_html.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaApplicationRoleSam'

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: bike_app
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      AutoVerifiedAttributes:
        - email
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
            AllowAdminCreateUserOnly: true
      
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: bike_app_client
      UserPoolId: !Ref CognitoUserPool
      AccessTokenValidity: 5
      IdTokenValidity: 1
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      AllowedOAuthFlowsUserPoolClient: true  
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - https://2f43f167e9944e5e9ada5580324b351f.vfs.cloud9.us-west-2.amazonaws.com # REPLACE WITH BIKE APP URL
      LogoutURLs:
        - https://2f43f167e9944e5e9ada5580324b351f.vfs.cloud9.us-west-2.amazonaws.com # REPLACE WITH BIKE APP URL
      SupportedIdentityProviders:
        - COGNITO

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "bike-app-domain-auth-${AWS::AccountId}"
      UserPoolId: !Ref CognitoUserPool

Outputs:
  EndpointForCreateReport:
    Description: "API Gateway endpoint URL for Prod stage for Create Report"
    Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/create-report"

  StateMachineArn:
    Description: "Step Functions state machine arn for email report"
    Value: !Ref StateMachine

  MicroserviceApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  GetProductsFunction:
    Description: "Get_Products Lambda Function ARN"
    Value: !GetAtt GetProductsFunction.Arn
  EndpointForGetProducts:
    Description: "API Gateway endpoint URL for Prod stage for Get_Products function"
    Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_products"
  EndpointForGetOrders:
      Description: "API Gateway endpoint URL for Prod stage for Get Order History"
      Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
  EndpointForGetOrderDetails:
    Description: "API Gateway endpoint URL for Prod stage for Get Order Details"
    Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders/{order_id}"
  EndpointForCreateOrder:
    Description: "API Gateway endpoint URL for Prod stage for Create Order"
    Value: !Sub "https://${BikeAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
  CognitoUserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPool
  CognitoUserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref CognitoUserPoolClient
  CognitoUserPoolDomain:
    Description: "Cognito User Pool Domain"
    Value: !Ref CognitoUserPoolDomain